const API_CONSTANTS = {
  LOGIN: 'LOGIN',
  DETAILS_SPECEFIC: 'DETAILS_SPECEFIC',
  DEPARTMENT_LIST: 'DEPARTMENT_LIST',
  CATEGORY_LIST: 'CATEGORY_LIST',
  USER_LIST: 'USER_LIST',
  COMPLAINT_LIST: 'COMPLAINT_LIST',
  ORGANZIATION_LIST: 'ORGANZIATION_LIST',
  ASK_FOR_UPDATE: 'ASK_FOR_UPDATE',
};

export default API_CONSTANTS;
