export const {
  VITE_REACT_APP_GOOGLE_CLIENT_ID: REACT_APP_GOOGLE_CLIENT_ID,
  VITE_REACT_APP_API_BASE_URL: REACT_APP_API_BASE_URL,
  REACT_APP_AWS_REGION = '',
  REACT_APP_AWS_ACCESS_KEY = '',
  REACT_APP_AWS_SECRECT_KEY = '',
  REACT_APP_S3_BUCKET_NAME = '',
} = import.meta.env;
